# Generated by Django 3.0.7 on 2020-06-19 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorielCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriel_categorie', models.CharField(max_length=200)),
                ('categories_sommaire', models.CharField(max_length=200)),
                ('categorie_slug', models.CharField(max_length=200)),
                ('categorie_image', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TutorielSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriel_series', models.CharField(max_length=200)),
                ('series_sommaire', models.CharField(max_length=200)),
                ('tutoriel_categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorielCategorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_tutoriel', models.CharField(max_length=200)),
                ('content_tutoriel', models.TextField()),
                ('publication_tutoriel', models.DateTimeField(default=datetime.datetime.now, verbose_name='date de publication')),
                ('tutoriel_slug', models.CharField(default=1, max_length=200)),
                ('tutoriel_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorielSeries', verbose_name='Series')),
            ],
        ),
    ]
