# Generated by Django 3.0.7 on 2020-06-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorielcategorie',
            name='categorie_image',
        ),
    ]
